version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: listly-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: listly
      MYSQL_USER: listly
      MYSQL_PASSWORD: listly
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
